# Generated by Django 2.0.2 on 2018-03-09 12:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键')),
                ('merchantName', models.CharField(db_column='merchant_name', max_length=64, verbose_name='商户名称')),
                ('price', models.DecimalField(db_column='sale_price', decimal_places=2, max_digits=18, verbose_name='价格')),
                ('recordTime', models.DateTimeField(db_column='record_time', default=datetime.datetime(2018, 3, 9, 20, 51, 37, 415804), verbose_name='爬取时间')),
                ('coin_type', models.IntegerField(choices=[(1, 'ETC'), (2, 'BTC')])),
            ],
            options={
                'db_table': 'coin_price_data',
            },
        ),
        migrations.CreateModel(
            name='SendConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendEmail', models.BooleanField(db_column='send_email', default=True)),
                ('sendSms', models.BooleanField(db_column='send_sms', default=True)),
                ('coin_type', models.IntegerField(choices=[(1, 'ETC'), (2, 'BTC')], default=1)),
                ('buyPrice', models.DecimalField(db_column='buy_price', decimal_places=2, max_digits=18)),
                ('salePrice', models.DecimalField(db_column='sale_price', decimal_places=2, max_digits=18)),
                ('createTime', models.DateTimeField(db_column='create_time', default=datetime.datetime(2018, 3, 9, 20, 51, 37, 414804))),
                ('lastModifyTime', models.DateTimeField(db_column='last_modify_time', default=datetime.datetime(2018, 3, 9, 20, 51, 37, 414804))),
            ],
            options={
                'db_table': 'coin_send_config',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键')),
                ('module', models.IntegerField(choices=[(1, '邮件'), (2, '短信')])),
                ('paramCode', models.CharField(db_column='param_code', max_length=64)),
                ('paramValue', models.CharField(db_column='param_value', max_length=64)),
                ('paramDesc', models.CharField(db_column='param_desc', max_length=128)),
                ('createTime', models.DateTimeField(db_column='create_time', default=datetime.datetime(2018, 3, 9, 20, 51, 37, 416804))),
                ('lastModifyTime', models.DateTimeField(db_column='last_modify_time', default=datetime.datetime(2018, 3, 9, 20, 51, 37, 416804))),
            ],
            options={
                'db_table': 'coin_system_config',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='user_name', max_length=64)),
                ('password', models.CharField(default='', max_length=64)),
                ('realName', models.CharField(db_column='real_name', max_length=64)),
                ('email', models.CharField(max_length=32, null=True)),
                ('phone', models.CharField(max_length=32, null=True)),
                ('createTime', models.DateTimeField(db_column='create_time', default=datetime.datetime(2018, 3, 9, 20, 51, 37, 413804))),
                ('lastModifyTime', models.DateTimeField(db_column='last_modify_time', default=datetime.datetime(2018, 3, 9, 20, 51, 37, 413804))),
            ],
            options={
                'db_table': 'coin_user',
            },
        ),
        migrations.AddField(
            model_name='sendconfig',
            name='user',
            field=models.ForeignKey(db_column='user_id', db_constraint=False, db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, to='coin.User'),
        ),
    ]
