# Generated by Django 2.0.2 on 2018-03-09 12:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricedata',
            name='coin_type',
        ),
        migrations.RemoveField(
            model_name='sendconfig',
            name='coin_type',
        ),
        migrations.AddField(
            model_name='pricedata',
            name='coinType',
            field=models.IntegerField(choices=[(1, 'ETC'), (2, 'BTC')], db_column='coin_type', default=1),
        ),
        migrations.AddField(
            model_name='sendconfig',
            name='coinType',
            field=models.IntegerField(choices=[(1, 'ETC'), (2, 'BTC')], db_column='coin_type', default=1),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='recordTime',
            field=models.DateTimeField(db_column='record_time', default=datetime.datetime(2018, 3, 9, 20, 55, 2, 315804), verbose_name='爬取时间'),
        ),
        migrations.AlterField(
            model_name='sendconfig',
            name='createTime',
            field=models.DateTimeField(db_column='create_time', default=datetime.datetime(2018, 3, 9, 20, 55, 2, 314804)),
        ),
        migrations.AlterField(
            model_name='sendconfig',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sendconfig',
            name='lastModifyTime',
            field=models.DateTimeField(db_column='last_modify_time', default=datetime.datetime(2018, 3, 9, 20, 55, 2, 314804)),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='createTime',
            field=models.DateTimeField(db_column='create_time', default=datetime.datetime(2018, 3, 9, 20, 55, 2, 316804)),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='lastModifyTime',
            field=models.DateTimeField(db_column='last_modify_time', default=datetime.datetime(2018, 3, 9, 20, 55, 2, 316804)),
        ),
        migrations.AlterField(
            model_name='user',
            name='createTime',
            field=models.DateTimeField(db_column='create_time', default=datetime.datetime(2018, 3, 9, 20, 55, 2, 313804)),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastModifyTime',
            field=models.DateTimeField(db_column='last_modify_time', default=datetime.datetime(2018, 3, 9, 20, 55, 2, 313804)),
        ),
    ]
