# Generated by Django 2.0.2 on 2018-03-10 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_auto_20180309_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricedata',
            name='priceType',
            field=models.IntegerField(choices=[(1, '买入'), (2, '卖出')], db_column='price_type', default=1),
        ),
        migrations.AddField(
            model_name='pricedata',
            name='rate',
            field=models.DecimalField(db_column='rate', decimal_places=3, default=0, max_digits=18, verbose_name='汇率'),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='coinType',
            field=models.IntegerField(choices=[(1, 'USDT')], db_column='coin_type', default=1),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='price',
            field=models.DecimalField(db_column='price', decimal_places=3, max_digits=18, verbose_name='价格'),
        ),
        migrations.AlterField(
            model_name='pricedata',
            name='recordTime',
            field=models.DateTimeField(db_column='record_time', default=datetime.datetime(2018, 3, 10, 21, 16, 53, 124803), verbose_name='爬取时间'),
        ),
        migrations.AlterField(
            model_name='sendconfig',
            name='coinType',
            field=models.IntegerField(choices=[(1, 'USDT')], db_column='coin_type', default=1),
        ),
        migrations.AlterField(
            model_name='sendconfig',
            name='createTime',
            field=models.DateTimeField(db_column='create_time', default=datetime.datetime(2018, 3, 10, 21, 16, 53, 123803)),
        ),
        migrations.AlterField(
            model_name='sendconfig',
            name='lastModifyTime',
            field=models.DateTimeField(db_column='last_modify_time', default=datetime.datetime(2018, 3, 10, 21, 16, 53, 124803)),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='createTime',
            field=models.DateTimeField(db_column='create_time', default=datetime.datetime(2018, 3, 10, 21, 16, 53, 126803)),
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='lastModifyTime',
            field=models.DateTimeField(db_column='last_modify_time', default=datetime.datetime(2018, 3, 10, 21, 16, 53, 126803)),
        ),
        migrations.AlterField(
            model_name='user',
            name='createTime',
            field=models.DateTimeField(db_column='create_time', default=datetime.datetime(2018, 3, 10, 21, 16, 53, 122803)),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastModifyTime',
            field=models.DateTimeField(db_column='last_modify_time', default=datetime.datetime(2018, 3, 10, 21, 16, 53, 122803)),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64),
        ),
    ]
